import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/tony/general/header";
import Sidebar from "@/components/tony/general/sidebar";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google";
import QueryProvider from "@/components/tony/general/query-provider";
// const inter = Inter({ subsets: ["latin"] });
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// console.log(fontSans.variable);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <QueryProvider>
          <Sidebar />
          <section className="flex  w-full flex-col py-3">
            {/* max-h-[100vh] */}
            <Header />
            <div className="flex-1 overflow-y-auto">{children}</div>
          </section>

          <ReactQueryDevtools initialIsOpen={false} />
        </QueryProvider>
      </body>
    </html>
  );
}
